name: 'Testing config import module'
type: module
description: 'Tests install profiles in the config importer.'
# version: VERSION
package: Testing

# Information added by Drupal.org packaging script on 2024-08-02
version: '11.0.0'
project: 'drupal'
datestamp: 1722578557
