name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2024-08-02
version: '11.0.0'
project: 'drupal'
datestamp: 1722578557
